  packages:
  - '**'
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/coverage/**'
  - '!**/playwright-report/**'
  - '!**/test-results/**'

  onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - msw
  